### ISSUE TITLE
Added @adobe/node-fetch-retry to DefinitelyTyped

### ISSUE THREAD

**Issue by ricardoatsouza** [adobe/node-fetch-retry#25]
Hello all,

I have created a type definition of your package in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48579). Since this concerns your package, it's more than natural to kindly ask for your review. :)

Also, I have added myself as a definition owner. I can keep up with the responsibility, but I believe it makes sense for the main contributors of this package to be there as well. Please, let me know which other github usernames I should add to it.

Cheers,

**Comment by jdelbick** [comment]
Hello @ricardoatsouza,

Thank you for creating this issue, but we won't manage or support those definitions.

Cheers :)

**Comment by ricardoatsouza** [comment]
Hello @jdelbick ,

That's unfortunate, but thanks for the reply. :)
