### ISSUE TITLE
How to use node-fetch-retry with @adobe/helix-fetch

### ISSUE THREAD

**Issue by trieloff** [adobe/node-fetch-retry#75]
I'm working on a project with @alexkli and we would like to use @stefan-guggisberg's https://github.com/adobe/helix-fetch but also use this project's retry functionality.

This project has `node-fetch` hardcoded as a dependency, but as the dependency footprint is small, it should theoretically be possible to use a different fetch implementation.

I've tried using npm 8.3's [`override` functionality](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) to make replace `node-fetch` transparently with `@adobe/helix-fetch`, but ran into subtle incompatibilities:

- `node-fetch` exports `fetch` as a default export, in `@adobe/helix-fetch` it is `{ fetch }`
- `node-fetch` can be `require`d, `@adobe/helix-fetch` needs to be `import`ed

I could imagine a pull request that would 
1. turn `node-fetch` into a peer dependency
2. support an `options.fetch` parameter that allows passing a `fetch` implementation
3. uses `node-fetch` as the default for this parameter
4. `require()`s `node-fetch` dynamically (so that it is optional, but that might make packaging a bit more difficult)

**Comment by trieloff** [comment]
Thinking this a bit further, it would be cool to have the ability to run the entire library in the browser, using `window.fetch`

**Comment by stefan-guggisberg** [comment]
> node-fetch can be required, @adobe/helix-fetch needs to be imported

@trieloff Why do you think that `@adobe/helix-fetch`needs to be imported?.  The following code works without any issues:

```js
const { fetch, reset } = require('@adobe/helix-fetch');

fetch('http://example.com')
  .then(async (resp) => console.log(`${resp.status} - ${await resp.text()}`))
  .finally(reset);
```

**Comment by stefan-guggisberg** [comment]
If the `node-fetch` dependency is going to be optional it would IMO make sense to make `abort-controller` optional as well.

**Comment by tmathern** [comment]
Is browser support "just cool" or needed for your project?

**Comment by tmathern** [comment]
Opened issue: [ASSETS-9903](https://jira.corp.adobe.com/browse/ASSETS-9903)

**Comment by alexkli** [comment]
> Is browser support "just cool" or needed for your project?

Not needed for helix-fetch in particular.

But it might be useful to have this project support browsers as well, if possible (might need to be renamed to `fetch-retry` then).

**Comment by alexkli** [comment]
Closing in favor of #86.
