### ISSUE TITLE
Logging and error behavior

### ISSUE THREAD

**Issue by Mazus** [adobe/node-fetch-retry#76]
Sorry that is not really an issue, but I need a clarification on how things are supposed to work.
If I have a "await fetch" with a .catch()
Does the .catch overrides the retry behavior? And if not, how can I do to check if a retry actually happened ?

Thanks.

**Comment by alexkli** [comment]
If there is an error that is retried (depends on `retryOnHttpResponse` and `retryOnHttpError` if set in the config), it will retry  the request. At that point your client code will still be awaiting the `fetch()` call. Only after the retry ends will it return to your code. This could be either
- the request succeeded: you get the successful request results
- the (last retried) request failed: you get the error from that failed request. this depends on the type of "error" but is just like plain fetch()
  - either throws if it's a FetchError in case of OS/TCP/network level errors. this is what `retryOnHttpError` handles
  - returns a response with `response.ok == false` in case of a non-success HTTP response. this is what `retryOnHttpResponse` handles
  
HTH! Closing the issue as this was a question.

**Comment by Mazus** [comment]
Thanks for the explanation.
However, it does mean that we have no way of tracing if there were any retries ?
Thanks

**Comment by alexkli** [comment]
See #77
